export const GET_ACTOR_BY_ID = "GET_ACTOR_BY_ID";
export const GET_ACTOR_MOVIES_SHOWS = "GET_ACTOR_MOVIES_SHOWS";
export const GET_POPULAR_ACTORS = "GET_POPULAR_ACTORS";
export const SET_ACTORS_ERROR = "SET_ACTORS_ERROR";
export const CLEAR_ACTOR = "CLEAR_ACTOR";
